FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
COPY Yals/Yals.csproj Yals/
RUN dotnet restore Yals/Yals.csproj
COPY Yals/ Yals/
WORKDIR /app/Yals
ENTRYPOINT ["dotnet", "ef", "database", "update"]
